server:
  port: 8082

# todo 如果item对应地址发生变化，就需要修改配置文件
# todo 如果有多个item地址，想要实现负载均衡，如何配置
myspcloud:
  item:
    url: http://127.0.0.1:8081/item/

###服务名称(该服务注册到eureka注册中心的名称，比如订单服务)
spring:
  application:
    name: app-order
###服务注册到eureka注册中心的地址
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8100/eureka
    ###因为该应用为服务提供者，是eureka的一个客户端，需要注册到注册中心
    register-with-eureka: true
    ###是否需要从eureka上检索服务
    fetch-registry: true
